import pandas as pd
import numpy as np
import talib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

def talib_index(df):
    df = df.astype('float')
    df['DEMA'] = talib.DEMA(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['upperband'], df['middleband'], df['lowerband'] = talib.BBANDS(np.array(df['Close']), timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)[-1*len(df):]
    df['EMA'] = talib.EMA(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['HT_TRENDLINE'] = talib.HT_TRENDLINE(np.array(df['Close']))[-1*len(df):]
    df['KAMA'] = talib.KAMA(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['MA'] = talib.MA(np.array(df['Close']), timeperiod=30, matype=0)[-1*len(df):]
    #df['mama'], df['fama'] = talib.MAMA(np.array(df['Close']), fastlimit=0, slowlimit=0)[-1*len(df):]
    #df['MAVP'] = talib.MAVP(np.array(df['Close']), periods, minperiod=2, maxperiod=30, matype=0)[-1*len(df):]
    df['MIDPOINT'] = talib.MIDPOINT(np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['MIDPRICE'] = talib.MIDPRICE(np.array(df['High']), np.array(df['Low']), timeperiod=14)[-1*len(df):]
    df['SAR'] = talib.SAR(np.array(df['High']), np.array(df['Low']), acceleration=0, maximum=0)[-1*len(df):]
    df['SAREXT'] = talib.SAREXT(np.array(df['High']), np.array(df['Low']), startvalue=0, offsetonreverse=0, accelerationinitlong=0, accelerationlong=0, accelerationmaxlong=0, accelerationinitshort=0, accelerationshort=0, accelerationmaxshort=0)[-1*len(df):]
    df['SMA'] = talib.SMA(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    #df['T3'] = talib.T3(np.array(df['Close']), timeperiod=5, vfactor=0)[-1*len(df):]
    # df['TEMA'] = talib.TEMA(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['TRIMA'] = talib.TRIMA(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['WMA'] = talib.WMA(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['ADX'] = talib.ADX(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['ADXR'] = talib.ADXR(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['APO'] = talib.APO(np.array(df['Close']), fastperiod=12, slowperiod=26, matype=0)[-1*len(df):]
    df['aroondown'], df['aroonup'] = talib.AROON(np.array(df['High']), np.array(df['Low']), timeperiod=14)[-1*len(df):]
    df['AROONOSC'] = talib.AROONOSC(np.array(df['High']), np.array(df['Low']), timeperiod=14)[-1*len(df):]
    df['BOP'] = talib.BOP(np.array(df['Open']), np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CCI'] = talib.CCI(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['CMO'] = talib.CMO(np.array(df['Close']), timeperiod=14)[-1*len(df):]
    #df['DX'] = talib.DX(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['MACD'], df['macdsignal'], df['macdhist'] = talib.MACD(np.array(df['Close']), fastperiod=12, slowperiod=26, signalperiod=9)[-1*len(df):]
    df['macdEXT'], df['macdsignalEXT'], df['macdhistEXT'] = talib.MACDEXT(np.array(df['Close']), fastperiod=12, fastmatype=0, slowperiod=26, slowmatype=0, signalperiod=9, signalmatype=0)[-1*len(df):]
    df['macdFIX'], df['macdsignalFIX'], df['macdhistFIX'] = talib.MACDFIX(np.array(df['Close']), signalperiod=9)[-1*len(df):]
    #df['MFI'] = talib.MFI(np.array(df['High']), np.array(df['Low']), np.array(df['Close']),  np.array(df['Volume']), timeperiod=14)[-1*len(df):]
    #df['MINUS_DI'] = talib.MINUS_DI(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    #df['MINUS_DM'] = talib.MINUS_DM(np.array(df['High']), np.array(df['Low']), timeperiod=14)[-1*len(df):]
    df['MOM'] = talib.MOM(np.array(df['Close']), timeperiod=10)[-1*len(df):]
    #df['PLUS_DI'] = talib.PLUS_DI(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    #df['PLUS_DM'] = talib.PLUS_DM(np.array(df['High']), np.array(df['Low']), timeperiod=14)[-1*len(df):]
    df['PPO'] = talib.PPO(np.array(df['Close']), fastperiod=12, slowperiod=26, matype=0)[-1*len(df):]
    df['RPC'] = talib.ROC(np.array(df['Close']), timeperiod=10)[-1*len(df):]
    df['ROCP'] = talib.ROCP(np.array(df['Close']), timeperiod=10)[-1*len(df):]
    df['ROCR'] = talib.ROCR(np.array(df['Close']), timeperiod=10)[-1*len(df):]
    df['ROCR100'] = talib.ROCR100(np.array(df['Close']), timeperiod=10)[-1*len(df):]
    df['RSI'] = talib.RSI(np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['slowk'], df['slowd'] = talib.STOCH(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)[-1*len(df):]
    df['fastk'], df['fastd'] = talib.STOCHF(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), fastk_period=5, fastd_period=3, fastd_matype=0)[-1*len(df):]
    df['fastkRSI'], df['fastdRSI'] = talib.STOCHRSI(np.array(df['Close']), timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)[-1*len(df):]
    # df['TRIX'] = talib.TRIX(np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['ULTOSC'] = talib.ULTOSC(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod1=7, timeperiod2=14, timeperiod3=28)[-1*len(df):]
    df['WILLR'] = talib.WILLR(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['AD'] = talib.AD(np.array(df['High']), np.array(df['Low']), np.array(df['Close']),  np.array(df['Volume']))[-1*len(df):]
    df['ADOSC'] = talib.ADOSC(np.array(df['High']), np.array(df['Low']), np.array(df['Close']),  np.array(df['Volume']), fastperiod=3, slowperiod=10)[-1*len(df):]
    df['OBV'] = talib.OBV(np.array(df['Close']),  np.array(df['Volume']))[-1*len(df):]
    #df['HT_DCPERIOD'] = talib.HT_DCPERIOD(np.array(df['Close']))[-1*len(df):]
    #df['HT_DCPHASE'] = talib.HT_DCPHASE(np.array(df['Close']))[-1*len(df):]
    #df['inphase'], df['quadrature'] = talib.HT_PHASOR(np.array(df['Close']))[-1*len(df):]
    #df['sine'], df['leadsine'] = talib.HT_SINE(np.array(df['Close']))[-1*len(df):]
    #df['HT_TRENDMODE'] = talib.HT_TRENDMODE(np.array(df['Close']))[-1*len(df):]
    df['AVGPRICE'] = talib.AVGPRICE(np.array(df['Open']), np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['MEDPRICE'] = talib.MEDPRICE(np.array(df['High']), np.array(df['Low']))[-1*len(df):]
    df['TYPPRICE'] = talib.TYPPRICE(np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['WCLPRICE'] = talib.WCLPRICE(np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    #df['ATR'] = talib.ATR(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    #df['NATR'] = talib.NATR(np.array(df['High']), np.array(df['Low']), np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['TRANGE'] = talib.TRANGE(np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDL2CROWS'] = talib.CDL2CROWS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDL3BLACKCROWS'] = talib.CDL3BLACKCROWS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDL3INSIDE'] = talib.CDL3INSIDE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDL3LINESTRIKE'] = talib.CDL3LINESTRIKE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDL3OUTSIDE'] = talib.CDL3OUTSIDE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDL3STARSINSOUTH'] = talib.CDL3STARSINSOUTH( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDL3WHITESOLDIERS'] = talib.CDL3WHITESOLDIERS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLABANDONEDBABY'] = talib.CDLABANDONEDBABY( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']), penetration=0)[-1*len(df):]
    df['CDLADVANCEBLOCK'] = talib.CDLADVANCEBLOCK( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLBELTHOLD'] = talib.CDLBELTHOLD( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLBREAKAWAY'] = talib.CDLBREAKAWAY( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLCLOSINGMARUBOZU'] = talib.CDLCLOSINGMARUBOZU( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLCONCEALBABYSWALL'] = talib.CDLCONCEALBABYSWALL( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLCOUNTERATTACK'] = talib.CDLCOUNTERATTACK( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLDARKCLOUDCOVER'] = talib.CDLDARKCLOUDCOVER( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']), penetration=0)[-1*len(df):]
    df['CDLDOJI'] = talib.CDLDOJI( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLDOJISTAR'] = talib.CDLDOJISTAR( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLDRAGONFLYDOJI'] = talib.CDLDRAGONFLYDOJI( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLENGULFING'] = talib.CDLENGULFING( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLEVENINGDOJISTAR'] = talib.CDLEVENINGDOJISTAR( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']), penetration=0)[-1*len(df):]
    df['CDLEVENINGSTAR'] = talib.CDLEVENINGSTAR( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']), penetration=0)[-1*len(df):]
    df['CDLGAPSIDESIDEWHITE'] = talib.CDLGAPSIDESIDEWHITE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLGRAVESTONEDOJI'] = talib.CDLGRAVESTONEDOJI( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHAMMER'] = talib.CDLHAMMER( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHANGINGMAN'] = talib.CDLHANGINGMAN( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHARAMI'] = talib.CDLHARAMI( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHARAMICROSS'] = talib.CDLHARAMICROSS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHIGHWAVE'] = talib.CDLHIGHWAVE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHIKKAKE'] = talib.CDLHIKKAKE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHIKKAKEMOD'] = talib.CDLHIKKAKEMOD( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLHOMINGPIGEON'] = talib.CDLHOMINGPIGEON( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLIDENTICAL3CROWS'] = talib.CDLIDENTICAL3CROWS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLINNECK'] = talib.CDLINNECK( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLINVERTEDHAMMER'] = talib.CDLINVERTEDHAMMER( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLKICKING'] = talib.CDLKICKING( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLKICKINGBYLENGTH'] = talib.CDLKICKINGBYLENGTH( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLLADDERBOTTOM'] = talib.CDLLADDERBOTTOM( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLLONGLEGGEDDOJI'] = talib.CDLLONGLEGGEDDOJI( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLLONGLINE'] = talib.CDLLONGLINE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLMARUBOZU'] = talib.CDLMARUBOZU( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLMATCHINGLOW'] = talib.CDLMATCHINGLOW( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLMATHOLD'] = talib.CDLMATHOLD( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']), penetration=0)[-1*len(df):]
    df['CDLMORNINGDOJISTAR'] = talib.CDLMORNINGDOJISTAR( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']), penetration=0)[-1*len(df):]
    df['CDLMORNINGSTAR'] = talib.CDLMORNINGSTAR( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']), penetration=0)[-1*len(df):]
    df['CDLONNECK'] = talib.CDLONNECK( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLPIERCING'] = talib.CDLPIERCING( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLRICKSHAWMAN'] = talib.CDLRICKSHAWMAN( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLRISEFALL3METHODS'] = talib.CDLRISEFALL3METHODS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLSEPARATINGLINES'] = talib.CDLSEPARATINGLINES( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLSHOOTINGSTAR'] = talib.CDLSHOOTINGSTAR( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLSHORTLINE'] = talib.CDLSHORTLINE( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLSPINNINGTOP'] = talib.CDLSPINNINGTOP( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLSTALLEDPATTERN'] = talib.CDLSTALLEDPATTERN( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLSTICKSANDWICH'] = talib.CDLSTICKSANDWICH( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLTAKURI'] = talib.CDLTAKURI( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLTASUKIGAP'] = talib.CDLTASUKIGAP( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLTHRUSTING'] = talib.CDLTHRUSTING( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLTRISTAR'] = talib.CDLTRISTAR( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLUNIQUE3RIVER'] = talib.CDLUNIQUE3RIVER( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLUPSIDEGAP2CROWS'] = talib.CDLUPSIDEGAP2CROWS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['CDLXSIDEGAP3METHODS'] = talib.CDLXSIDEGAP3METHODS( np.array(df['Open']),  np.array(df['High']), np.array(df['Low']), np.array(df['Close']))[-1*len(df):]
    df['BETA'] = talib.BETA( np.array(df['High']), np.array(df['Low']), timeperiod=5)[-1*len(df):]
    df['CORREL'] = talib.CORREL( np.array(df['High']), np.array(df['Low']), timeperiod=30)[-1*len(df):]
    df['LINEARREG'] = talib.LINEARREG( np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['LINEARREG_ANGLE'] = talib.LINEARREG_ANGLE( np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['LINEARREG_INTERCEPT'] = talib.LINEARREG_INTERCEPT( np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['LINEARREG_SLOPE'] = talib.LINEARREG_SLOPE( np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['STDDEV'] = talib.STDDEV( np.array(df['Close']), timeperiod=5, nbdev=1)[-1*len(df):]
    df['TSF'] = talib.TSF( np.array(df['Close']), timeperiod=14)[-1*len(df):]
    df['VAR'] = talib.VAR( np.array(df['Close']), timeperiod=5, nbdev=1)[-1*len(df):]
    # df['ASCO'] = talib.ACOS( np.array(df['Close']))[-1*len(df):]
    # df['ASIN'] = talib.ASIN( np.array(df['Close']))[-1*len(df):]
    df['ATAN'] = talib.ATAN( np.array(df['Close']))[-1*len(df):]
    df['CEIL'] = talib.CEIL( np.array(df['Close']))[-1*len(df):]
    df['COS'] = talib.COS( np.array(df['Close']))[-1*len(df):]
    df['COSH'] = talib.COSH( np.array(df['Close']))[-1*len(df):]
    df['EXP'] = talib.EXP( np.array(df['Close']))[-1*len(df):]
    df['FLOOR'] = talib.FLOOR( np.array(df['Close']))[-1*len(df):]
    df['LN'] = talib.LN( np.array(df['Close']))[-1*len(df):]
    df['LOG10'] = talib.LOG10( np.array(df['Close']))[-1*len(df):]
    df['SIN'] = talib.SIN( np.array(df['Close']))[-1*len(df):]
    df['SINH'] = talib.SINH( np.array(df['Close']))[-1*len(df):]
    df['SQRT'] = talib.SQRT( np.array(df['Close']))[-1*len(df):]
    df['TAN'] = talib.TAN( np.array(df['Close']))[-1*len(df):]
    df['TANH'] = talib.TANH( np.array(df['Close']))[-1*len(df):]
    df['ADD'] = talib.ADD( np.array(df['High']), np.array(df['Low']))[-1*len(df):]
    df['DIV'] = talib.DIV( np.array(df['High']), np.array(df['Low']))[-1*len(df):]
    df['MAX'] = talib.MAX( np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['MAXINDEX'] = talib.MAXINDEX( np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['MIN'] = talib.MIN( np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['MININDEX'] = talib.MININDEX( np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['min'], df['max'] = talib.MINMAX( np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['minidx'], df['maxidx'] = talib.MINMAXINDEX( np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df['MULT'] = talib.MULT( np.array(df['High']), np.array(df['Low']))[-1*len(df):]
    df['SUB'] = talib.SUB( np.array(df['High']), np.array(df['Low']))[-1*len(df):]
    df['SUM'] = talib.SUM( np.array(df['Close']), timeperiod=30)[-1*len(df):]
    df = df.fillna(0)
    return df
